{ config, lib, pkgs, ... }:

# Quickshell desktop shell: control center (SUPER+B), app launcher (SUPER+R),
# notification popups and a workspace OSD. There is no permanent bar;
# nothing is visible until used.
#
# QML lives in ./config and is linked to ~/.config/quickshell/luna.
# Live-edit while developing:  qs -p ~/nixos/dotfiles/home/luna/modules/quickshell/config
let
  configName = "luna";
  target = "hyprland-session.target";

  # Official Claude Desktop Linux build, for the launcher's Claude card.
  claude-desktop = pkgs.callPackage ./packages/claude-desktop.nix { };

  # Plan usage for the Claude card (unofficial endpoint, read-only).
  qs-claude-usage = pkgs.writeShellApplication {
    name = "qs-claude-usage";
    runtimeInputs = with pkgs; [
      coreutils
      curl
      jq
    ];
    text = builtins.readFile ./scripts/qs-claude-usage.sh;
  };
in
{
  programs.quickshell = {
    enable = true;
    configs.${configName} = ./config;
    activeConfig = configName;
    systemd = {
      enable = true;
      inherit target;
    };
  };

  # Restart/stop together with the Hyprland session instead of lingering.
  systemd.user.services.quickshell.Unit.PartOf = [ target ];

  # Some app icons (e.g. those generated by JetBrains Toolbox) use SVG filter
  # regions Qt can't buffer; the icon still renders, but Qt SVG warns on
  # every draw. Silence only that category.
  systemd.user.services.quickshell.Service.Environment = [
    "QT_LOGGING_RULES=qt.svg.draw.warning=false"
  ];

  # Home Manager evaluates its own nixpkgs (no useGlobalPkgs), so the system's
  # allowUnfree doesn't apply here. Allow exactly this one unfree package.
  nixpkgs.config.allowUnfreePredicate = pkg: builtins.elem (lib.getName pkg) [ "claude-desktop" ];

  home.packages = with pkgs; [
    brightnessctl # brightness slider (also used by the XF86 brightness keys)
    hyprsunset # night light
    material-symbols # icon font (Material Symbols Rounded)
    rubik # UI font
    claude-desktop
    qs-claude-usage
  ];

  # The launcher picks up new apps through Quickshell's watcher on the XDG
  # application dirs. Profile switches replace symlinks higher up, so nudge
  # the watcher once per activation to be sure it rescans.
  home.activation.quickshellRescanApps = lib.hm.dag.entryAfter [ "linkGeneration" ] ''
    apps="${config.xdg.dataHome}/applications"
    run mkdir -p "$apps"
    run touch "$apps/.quickshell-rescan"
    run rm -f "$apps/.quickshell-rescan"
  '';

  # Make the user-profile fonts above visible to fontconfig.
  fonts.fontconfig.enable = true;

  wayland.windowManager.hyprland.settings = {
    bind = [
      {
        _args = [
          "SUPER + B"
          (lib.generators.mkLuaInline ''hl.dsp.global("quickshell:panelToggle")'')
        ];
      }
      {
        _args = [
          "SUPER + R"
          (lib.generators.mkLuaInline ''hl.dsp.global("quickshell:launcherToggle")'')
        ];
      }
    ];

    # The shell animates its own surfaces; Hyprland's layer animations would
    # run on top of that.
    layer_rule = [
      { match.namespace = "^quickshell-.*$"; no_anim = true; }
    ];
  };
}
