{ pkgs, lib, config, ... }:

let
  enableLiquidGlass = true;

  hypr = pkgs.hyprland;

  liquidGlassPlugin =
    pkgs.hyprlandPlugins.mkHyprlandPlugin (_finalAttrs: {
      pluginName = "liquid-glass";
      version = "git";

      src = pkgs.fetchFromGitHub {
        owner = "purple-lines";
        repo = "liquid-glass-plugin-hyprpm";
        rev = "main";
        sha256 = "sha256-awTwcDRSwV1HtBLA8+V+4exIFcqb2hmDzntlshd6Uf8=";
      };

      nativeBuildInputs = with pkgs; [
        pkg-config
        gnumake
      ];

      buildInputs = with pkgs; [
        pixman
        libdrm
        pango
        cairo
        libinput
        udev
        wayland
        libxkbcommon

        # Hyprland for pkg-config + source (we symlink the src below)
        hypr
      ];

      buildPhase = ''
                runHook preBuild

                # The plugin includes Hyprland internals as:
                #   <hyprland/src/...>
                # so we need a builddir-local "hyprland/" tree.
                if [ -e "${hypr.src or ""}" ] && [ -n "${hypr.src or ""}" ]; then
                  ln -sf "${hypr.src}" hyprland
                else
                  echo "ERROR: pkgs.hyprland has no .src attribute in this nixpkgs."
                  echo "Try pkgs.hyprland-unwrapped.src or pin/fetch Hyprland source."
                  exit 1
                fi

                # Because the headers are included with angle brackets, the current dir is
                # not searched unless we add it explicitly.
                export NIX_CFLAGS_COMPILE="$NIX_CFLAGS_COMPILE -I$PWD"

                # Hyprland's PluginAPI.hpp expects hyprland/src/version.h, but that file is
                # often generated at Hyprland build time and may not exist in the source tree.
                #
                # Try to locate an installed version.h inside the Hyprland package output and copy it,
                # otherwise generate a minimal stub to get the plugin to compile.
                if [ ! -f hyprland/src/version.h ]; then
                  echo "hyprland/src/version.h missing — trying to locate installed version.h in Hyprland package..."

                  found_version_h=""
                  # Search a bit in the Hyprland output; keep it shallow for speed.
                  found_version_h="$(find "${hypr}" -maxdepth 5 -type f -name version.h 2>/dev/null | head -n 1 || true)"

                  if [ -n "$found_version_h" ] && [ -f "$found_version_h" ]; then
                    echo "Found version.h at: $found_version_h"
                    mkdir -p hyprland/src
                    cp -f "$found_version_h" hyprland/src/version.h
                  else
                    echo "No installed version.h found — generating a minimal stub at hyprland/src/version.h"
                    mkdir -p hyprland/src
                    cat > hyprland/src/version.h <<'EOF'
        #pragma once

        // NOTE: This is a build-time stub generated by the Nix plugin build.
        // Hyprland normally generates version.h during its build.
        // If the plugin performs strict ABI/version checks at runtime, you might need
        // the real generated header matching your Hyprland build.

        #ifndef HYPRLAND_VERSION
        #define HYPRLAND_VERSION "unknown"
        #endif

        #ifndef HYPRLAND_VERSION_COMMIT
        #define HYPRLAND_VERSION_COMMIT "unknown"
        #endif

        #ifndef HYPRLAND_VERSION_DIRTY
        #define HYPRLAND_VERSION_DIRTY "0"
        #endif

        #ifndef HYPRLAND_VERSION_TAG
        #define HYPRLAND_VERSION_TAG "unknown"
        #endif
        EOF
                  fi
                fi

                make all

                runHook postBuild
      '';

      installPhase = ''
        runHook preInstall
        mkdir -p $out/lib
        install -m755 liquid-glass.so $out/lib/liquid-glass.so
        runHook postInstall
      '';

      meta = with lib; {
        description = "Apple-style Liquid Glass effect plugin for Hyprland";
        homepage = "https://github.com/purple-lines/liquid-glass-plugin-hyprpm";
        license = licenses.mit;
        platforms = platforms.linux;
      };
    });
in
{
  options.hyprMacos.enableLiquidGlass = lib.mkOption {
    type = lib.types.bool;
    default = enableLiquidGlass;
  };

  config = lib.mkMerge [
    (lib.mkIf config.hyprMacos.enableLiquidGlass {
      hyprMacos.liquidGlassPlugin = liquidGlassPlugin;
    })

    (lib.mkIf (!config.hyprMacos.enableLiquidGlass) {
      hyprMacos.liquidGlassPlugin = null;
    })
  ];
}
