{ inputs, config, lib, pkgs, ... }:
{
  imports = [
    ./vars.nix
    ./monitors.nix
    ./env.nix
    ./autostart.nix
    ./look.nix
    ./input.nix
    ./binds.nix
    ./rules.nix
    ./ghostty.nix
    ./hyprlock.nix
    ./hyprpaper.nix
    #./nwg-dock.nix
    ./starship.nix
    ./theme.nix
    ./waybar.nix
    ./wofi.nix
  ];

  wayland.windowManager.hyprland = {
    enable = true;
    # Hyprland + Portal kommen aus dem NixOS-Modul (programs.hyprland).
    # Sonst setzt Home-Manager NIX_XDG_DESKTOP_PORTAL_DIR auf das User-Profil,
    # das nur hyprland.portal enthält -> gtk-Portal & System-Config werden ignoriert.
    package = null;
    portalPackage = null;
    # hyprland.lua statt hyprland.conf (hyprlang fällt mit Hyprland 0.57 weg)
    configType = "lua";
  };

  # Eine noch laufende Session mit hyprland.conf legt beim Rebuild einen Stub
  # ("autogenerated = 1") an, sobald HM die alte Datei entfernt -> wegräumen.
  home.activation.removeHyprlandConfStub =
    lib.hm.dag.entryAfter [ "writeBoundary" ] ''
      conf="${config.xdg.configHome}/hypr/hyprland.conf"
      if [ -f "$conf" ] && [ ! -L "$conf" ] && grep -q '^autogenerated = 1' "$conf"; then
        run rm $VERBOSE_ARG "$conf"
      fi
    '';
}

